[package]
name = "bamnado"
version = "0.3.0"
edition = "2024"
license = "MIT OR Apache-2.0"
description = "Tools and utilities for manipulation of BAM files for unusual use cases. e.g. single cell, MCC"
repository = "https://github.com/alsmith151/BamNado"
homepage = "https://github.com/alsmith151/BamNado"
authors = ["Alastair Smith <alastair.smith@ndcls.ox.ac.uk>"]
readme = "README.md"
keywords = ["bioinformatics", "scATAC-seq", 'MCC']


[dependencies]
ahash = "0.8.12"
anyhow = "1.0.98"
bigtools = "0.5.6"
bio = "2.3.0"
bio-types = "1.0.1"
clap = {version = "4.5.40", features = ["derive"]}
colog = "1.3.0"
indicatif = {version = "0.17.11", features = ["rayon"]}
itertools = "0.14.0"
log = "0.4.27"
noodles = {version = '0.99.0', features = ['bgzf', 'cram','bed', 'core', 'csi', 'async', 'sam', 'bam']}
polars = {version = "0.49.1", features = ['lazy', "polars-ops", "cum_agg"]}
rayon = "1.10.0"
rust-lapper = "1.1.0"
tempfile = "3.20.0"
serde ={ version = "1.0.219", features = ["derive"]}
crossbeam = "0.8.4"
serde_json = "1.0.140"
sprs = "0.11.1"
ndarray = "0.16.1"
anstyle = "1.0.11"
futures = "0.3.31"
tokio = { version = "1.45.1"}
regex = "1.10.7"